In [1]:
import pandas as pd

In [2]:
delimiter = "\t"
path = 'data/WikiText-103.csv'
dtype = {'inp': str, 'gt': str}
df = pd.read_csv(path, dtype=dtype, delimiter=delimiter, na_filter=False)

In [3]:
df.iloc[0]

inp    valkyria
gt     valkyria
Name: 0, dtype: object

In [5]:
df.iloc[0,0], df.iloc[0,1]

('valkyria', 'valkyria')

In [7]:
sum(df["inp"] == df['gt']), len(df)

(86460763, 86460763)

In [2]:
import numpy as np
np.random.beta(1,4, None)

0.2348754489438628

In [3]:
import cv2

In [10]:
M = cv2.getRotationMatrix2D(center=(40, 40), angle=15, scale=1.0)

array([[ 0.96592583,  0.25881905, -8.98979486],
       [-0.25881905,  0.96592583, 11.71572875]])

|col_1|col_2|col_3|
|-|-|-|
|cos|sin|(1-cos)c_x - sin c_y|
|-sin|cos|c_xsin - cos_c_y + c_y|

In [13]:
40 * (M[0,0] - M[0,1] )

28.284271247461902

In [1]:
import torch

In [6]:
out = torch.rand((2,2))

In [7]:
c = out.new_tensor(3)

In [27]:
out[0,0]

tensor([0.2481, 0.2568, 0.2620, 0.2330])

In [37]:
r = []
for o in out:
    #print(o)
    #print(o.max(dim=1))
    r.append(o.max(dim=1)[0])
r = torch.stack(r)

In [40]:
t = r.new_tensor([0,1])

In [42]:
r.requires_grad

False

In [41]:
t.requires_grad

False

In [43]:
a = torch.tensor(1.0, requires_grad=True)
y = a ** 2
a_ = a.detach()
print(a_.grad)  # None，requires_grad=False
a_.requires_grad_()  # set a_.requires_grad = True
z = a_ * 3
y.backward()
z.backward()
print(a_.grad)  # tensor(3.)
print(a.grad)  # tensor(2.)

None
tensor(3.)
tensor(2.)


In [45]:
id(a), id(a_)

(1867697609344, 1867697608896)

In [1]:
"image-%09d".encode() % 100

b'image-000000100'

In [3]:
txt = "My name is Stale"

x = txt.encode()

print(x)

b'My name is Stale'


In [2]:
import numpy as np
import lmdb
import cv2

In [7]:
with lmdb.open("data/evaluation/SVTP") as env:
    txn = env.begin()
    cnt = 0
    s = set()
    for k, v in txn.cursor():
        if k.decode()[:5] == "label":
            #print(v.decode())
            #s.add(v.decode())
            cnt += 1
            continue
        elif k.decode()[:5] == "image":
            continue
        else:
            print(v.decode(), k.decode())
            break

    ''''
    label = "label-%09d".encode() % cnt
    image = "image-%09d".encode() % cnt
    imageBuf = np.frombuffer(txn.get(image), dtype=np.uint8)
    img = cv2.imdecode(imageBuf, cv2.IMREAD_GRAYSCALE)
    cv2.imshow("img", img)
    cv2.waitKey(0)
    print(txn.get(label).decode())
    '''

645 num-samples


In [8]:
import torch

In [11]:
a = torch.rand((2,3,4))

In [13]:
a.permute(0,2,1)

tensor([[[0.7437, 0.1919, 0.0991],
         [0.4415, 0.4861, 0.3461],
         [0.2982, 0.3380, 0.6890],
         [0.2138, 0.0515, 0.8499]],

        [[0.2088, 0.8637, 0.1351],
         [0.6373, 0.2476, 0.8351],
         [0.8631, 0.5879, 0.4406],
         [0.7077, 0.2757, 0.9863]]])

In [19]:
b = a[0]

In [23]:
(a @ b.T).shape

torch.Size([2, 3, 3])